version: 2

jobs:
  build:
    docker:
      - image: circleci/php:7.1-node-browsers
    working_directory: ~https://github.com/harikrishna-wal/test-project-circleci.git
    steps:
      - checkout
      - run: yarn install
