version: 2

jobs:
  build:
    docker:
      - image: circleci/php:7.1-node-browsers
    working_directory: ~/test-project-circleci
    steps:
      - checkout
      
   - store_test_results:
    path: /tmp/test-results
